Постройте мелкие сетки на гридах для подходящих компонентов
htmlacademy-htmlcss/1976751-device-35 pull request #10
Opened 2022-10-16 16:08 UTC by mis3rably

2022-10-17 16:55 UTC, pavel-nyukalo requested changes

2022-10-17 16:55 UTC, pavel-nyukalo commented on catalog.html
> +      <div class="main-container">
По кодгайду Академии у нас должно быть по 2 пробела отступами, сейчас получается по 3, стоит поправить везде

![image](https://user-images.githubusercontent.com/52506235/196234312-fe0031d4-9289-4077-adf7-8574ed574b65.png)

2022-10-17 16:55 UTC, pavel-nyukalo commented on catalog.html
> +                     </li>
Здесь предлагаю вложенные теги оформлять каждый на своей строке - так более читабельно. То есть:
```html
<li>
  <img>
  <a></a>
</li>
```

2022-10-17 16:55 UTC, pavel-niukalo commented on catalog.html
> +                           class="main-header-page-navigation-link">Контакты</a></li>
Ко всем вложенным относится

2022-10-17 16:55 UTC, pavel-nyukalo commented on catalog.html
> +                        </a>
Если есть видимый текст ("Назад"), то дублировать такой же с `visually-hidden` нет смысла - скринридер прочитает видимый текст. А вот если у нас есть например кнопка, в которой только картинка, то вот ей стоит добавлять скрытый текст с описанием кнопки

2022-10-17 16:55 UTC, pavel-niukalo commented on catalog.html
> +               <nav class="main-footer-social-links flex">
По спецификации `nav` это главная навигация сайта, поэтому много плодить `nav` тоже не стоит. Но ошибкой не является

2022-10-17 16:55 UTC, pavel-nyukalo commented on index.html
> +                  <span class="showcase-radio"></span>
Так же нам надо в разметку добавить остальные слайды

![image](https://user-images.githubusercontent.com/52506235/196236242-417d07f9-76f2-43b2-917c-475efdedcf21.png)

2022-10-17 16:55 UTC, pavel-nyukalo commented on index.html
> +                  </li>
Тут думаю подойдут ссылки вместо `div`, чтобы при нажатии на каждую нас перекидывало в конкретный каталог

2022-10-17 16:55 UTC, pavel-niukalo commented on index.html
>                 </div>
Тут так же надо добавить все варианты

![image](https://user-images.githubusercontent.com/52506235/196236745-f8f26a59-9a0c-4236-bacd-3a67ae27d814.png)

2022-10-17 16:55 UTC, pavel-niukalo commented on index.html
> +               </div>
Опираясь на стайлгайд, у нас тут должен быть интерактивный элемент

![image](https://user-images.githubusercontent.com/52506235/196237033-b089d5c8-cd37-401d-9497-3163c0cc2da6.png)

2022-10-17 16:55 UTC, pavel-niukalo commented on index.html
> +                        <img class="subscription-text-free-icon" src="images/green-tick.svg" alt="" width="14"
Больше походит на декоративное изображение

2022-10-17 17:28 UTC, mis3rably commented on catalog.html
> +                     </li>
Существует ли какой-то инструмент для такого типа форматирования? Встроенный в VSCode такое оформление не делает, другие инструменты что я нашёл в гугле - тоже

2022-10-17 17:30 UTC, mis3rably commented on catalog.html
> +                        </a>
Исправил

2022-10-17 17:32 UTC, mis3rably commented on catalog.html
> +      <div class="main-container">
Исправил

2022-10-17 17:34 UTC, mis3rably commented on catalog.html
> +               <nav class="main-footer-social-links flex">
Какой способ на Ваш взгляд тут будет более правильный, убрать `nav` оставив просто список?

2022-10-17 19:33 UTC, mis3rably commented on catalog.html
> +                           class="main-header-page-navigation-link">Контакты</a></li>
Исправил

2022-10-17 19:34 UTC, mis3rably commented on index.html
> +                  </li>
Исправил

2022-10-17 19:35 UTC, mis3rably commented on index.html
> +                  <span class="showcase-radio"></span>
Добавил, частично слайдер недоделан, т.к псевдоэлементы будут дальше

2022-10-17 19:35 UTC, mis3rably commented on index.html
>                 </div>
Добавил, частично слайдер недоделан, т.к псевдоэлементы будут дальше

2022-10-17 19:35 UTC, mis3rably commented on index.html
> +               </div>
Исправил

2022-10-17 19:36 UTC, mis3rably commented on index.html
> +                        <img class="subscription-text-free-icon" src="images/green-tick.svg" alt="" width="14"
Убрал до раздела с псевдоэлементами

2022-10-19 07:48 UTC, pavel-niukalo commented on catalog.html
> +                     </li>
`Prettier` точно можно настроить так, но его надо будет еще настроить для одиночных тегов - он по-умолчанию ставит закрывающий слеш - а по кодгайду Академии он не ставится для одиночных тегов

2022-10-19 07:49 UTC, pavel-nyukalo commented on catalog.html
> +               <nav class="main-footer-social-links flex">
Я бы да, убрал `nav` и оставил просто список

2022-10-19 08:15 UTC, pavel-nyukalo requested changes

2022-10-19 08:15 UTC, pavel-niukalo commented on index.html
> +            </li>
Тут лучше скрытое описание перенести внутрь кнопки, оно описывает именно действие кнопки.

Так же по [критерию](https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-03) у кнопок надо явно указывать `type`. Стоит пройтись по всем кнопкам и проверить

2022-10-19 08:15 UTC, pavel-nyukalo commented on index.html
> +            <h2 class="product-showcase-heading title">Худеем правильно!</h2>
Насчет кнопок "Следующая/предыдущая картинка". Они у нас должны быть одни на весь слайдер (так же как и пагинация в виде кругов снизу). Сейчас кнопки дублируются в каждом слайде. Застилизовать это будет легко, но вот написать логику на JS будет легче, если эти кнопки будут в единственном экземпляре, а не в каждом слайде.

То есть должно быть примерно такое:
```html
<section class="slider">
  <ol> <-- кнопки как раз
    ...
  </ol>
  
  <-- Здесь слайды -->
  
  <ol> <-- А это круги-пагинация
    ...
  </ol
</section>
```

2022-10-19 08:15 UTC, pavel-nyukalo commented on index.html
> +              <a href="#" class="product-selection-list-text-link">Виртуальная реальность</a>
Лучше сделать одной ссылкой, чтобы стилизовать поведение было проще (по стайлгайду картинка и текст как бы связанны)

![image](https://user-images.githubusercontent.com/52506235/196633280-30dc656d-d834-42e0-89d0-8504bef967f5.png)

2022-10-19 08:15 UTC, pavel-nyukalo commented on index.html
> +            <div class="nuances-item">
Тут аналогично с слайдером - кнопки "Доставка", "Гарантия" и "Кредит" должны быть одни на всю карусель/слайдер/как удобно называть

2022-10-19 08:15 UTC, pavel-nyukalo commented on index.html
> +               </li>
Нужно добавить отступы у дочерних тегов

2022-10-19 08:15 UTC, pavel-nyukalo commented on catalog.html
> +              </li>
Так же про отступы у дочерних

2022-10-19 09:48 UTC, mis3rably commented on catalog.html
> +               <nav class="main-footer-social-links flex">
Исправил

2022-10-19 09:53 UTC, mis3rably commented on index.html
> +            </li>
Исправил

2022-10-19 09:57 UTC, mis3rably commented on catalog.html
> +              </li>
Исправил

2022-10-19 09:58 UTC, mis3rably commented on index.html
> +               </li>
Исправил

2022-10-19 10:05 UTC, mis3rably commented on catalog.html
> +                     </li>
Буду разбираться

2022-10-19 10:50 UTC, mis3rably commented on index.html
> +            <h2 class="product-showcase-heading title">Худеем правильно!</h2>
Исправил

2022-10-19 11:02 UTC, mis3rably commented on index.html
> +              <a href="#" class="product-selection-list-text-link">Виртуальная реальность</a>
Исправил

2022-10-19 11:02 UTC, mis3rably commented on index.html
> +            <div class="nuances-item">
Исправил

2022-10-19 13:33 UTC, pavel-niukalo approved these changes

2022-10-19 13:33 UTC, merged