Стилизация декоративных элементов
htmlacademy-htmlcss/1976751-device-35 pull request #11
Opened 2022-10-27 09:51 UTC by mis3rably

2022-10-27 09:54 UTC, mis3rably commented on styles/styles.css
> +.main-header-page-navigation-link::after {
Для стилизации ссылок когда появляется подчёркивание снизу я хотел использовать border-bottom, но из-за letter-spacing у текста сбоку появляется пустое место и выходит не очень. Я сделал с помощью after псевдо-элемента, и задал ему ширину 96% от родителя. Получилось лучше, но всё же я думаю это неидеальный вариант. Как сделать по-другому?

2022-10-27 09:57 UTC, mis3rably commented on styles/styles.css
> +.product-showcase-item::after {
Цифру с номером сладера я реализовал с помощью псевдо-элемента и absolute позиционирования от родителя. По какой-то причине ссылка Контакты которая находится над ним перестаёт реагировать на hover частично, если отодвинуть чуть ниже то работает нормально, но тогда идёт несоответсвие по макету. Почему так происходит и как это решить?

2022-10-27 10:01 UTC, mis3rably commented on index.html
> +            <a href="catalog.html" class="main-header-page-navigation-button-link state-default flex">Каталог товаров
Проверяя focus-visible состояние элемента, я заметил что рамка снизу пропала. Тоже самое происходит в пагинации в каталоге. Если добавлять паддинги то выходит не очень, да и наверное есть вариант правильнее?

2022-10-27 10:03 UTC, mis3rably commented on index.html
> +              <button class="nuances-controls main-link nuances-controls-current" type="button">Доставка</button>
Черную обводку вокруг текущей ссылки в слайдере я сделал с помощью псевдо-элемента. При проверки работы focus-visible выделяется не вся обводка а только кнопка. Я честно уже не могу сообразить как реализовать этот элемент по-другому, помогите пожалуйста

2022-10-27 10:08 UTC, mis3rably commented on catalog.html
> +                  <a href="product.html" class="product-card-link">
Я долго пытался добиться чтобы фокус работал в соответствии с Стайлгайдом, сначала выделялись только картинка и текст а не весь элемент целиком, после я обернул всю карточку в ссылку и фокус пропал совсем)

2022-10-28 14:02 UTC, pavel-nyukalo requested changes

2022-10-28 14:02 UTC, pavel-niukalo commented on catalog.html
> +              <button class="main-header-page-navigation-button state-default" type="button">
Кнопку нельзя вкладывать в ссылки

![image](https://user-images.githubusercontent.com/52506235/198581579-dc35af20-c6c3-4423-bfee-744c2d35b73d.png)

2022-10-28 14:02 UTC, pavel-niukalo commented on index.html
> +              <button class="main-header-page-navigation-button state-default" type="button">
Здесь аналогично про запрет вложения кнопки в ссылки

2022-10-28 14:02 UTC, pavel-niukalo commented on index.html
> +            <a href="catalog.html" class="main-header-page-navigation-button-link state-default flex">Каталог товаров
Рамка снизу пропала, поскольку она уходит под `main`. Как варианты решения: 1) задать `z-index` кнопке, чтобы она явно была "выше" по слою чем `main` 2) задать шапке нижний паддинг, чтобы зарезервировать место для `outline`

2022-10-28 14:02 UTC, pavel-niukalo commented on index.html
> +              <button class="nuances-controls main-link nuances-controls-current" type="button">Доставка</button>
Тут я бы предложил вот эту черную обводку делать не псевдоэлементом, а растягивать кнопку саму. То есть текущая кнопка у нас будет больше обычной и с черной заливкой и тд. В таком случае мы сможем спокойно ее стилизовать при фокусе

2022-10-28 14:02 UTC, pavel-niukalo commented on styles/styles.css
> +.main-header-page-navigation-link::after {
Через псевдоэлемент хорошее решение, единственное, поскольку псевдоэлемент абсолютно спозиционирован и задан как псевдоэлемент ссылки, лучше дать именно ссылке `position: relative`. Поскольку абсолютно спозиционированный элемент ищет ближайшего родителя, у которого `position` отличный от `static`. И тогда можно дать 100% ширины, `left: 0`, в целом будет хорошо выглядеть

2022-10-28 14:02 UTC, pavel-niukalo commented on styles/styles.css
> +.product-showcase-item::after {
Какое-то странное поведение, видимо где-то происходит наложение, надо покопать и поиграть со стилями, позже смогу посмотреть. Пока как вариант, можно всему `header` дать `z-index: 1`, и это решит проблему

2022-10-28 14:02 UTC, pavel-nyukalo commented on styles/styles.css
> +	background-image: url(../images/green-tick.svg);
Для надежности лучше добавить кавычки во все `url` - `url("../")`

2022-10-28 14:02 UTC, pavel-nyukalo commented on styles/styles.css
> +    padding-left: 27px;
Лишние отступы

2022-10-28 14:02 UTC, pavel-nyukalo commented on styles/styles.css
> +    top: 192px;
Стоит везде проверить отступы

2022-10-28 14:02 UTC, pavel-nyukalo commented on styles/styles.css
> +main-footer-phone-number-link {
Точка пропущена - браузер думает, что это тег

2022-10-30 09:31 UTC, mis3rably commented on styles/styles.css
> +.main-header-page-navigation-link::after {
Исправил

2022-10-30 09:31 UTC, mis3rably commented on styles/styles.css
> +.product-showcase-item::after {
Спасибо, помогло)

2022-10-30 09:32 UTC, mis3rably commented on index.html
> +            <a href="catalog.html" class="main-header-page-navigation-button-link state-default flex">Каталог товаров
Помогло, спасибо, пагинации добавил каждой кнопке `z-index` при` focus-visible`

2022-10-30 09:33 UTC, mis3rably commented on index.html
> +              <button class="nuances-controls main-link nuances-controls-current" type="button">Доставка</button>
Исправил, спасибо) Вроде бы так просто а в голову совсем не приходило

2022-10-30 09:33 UTC, mis3rably commented on catalog.html
> +                  <a href="product.html" class="product-card-link">
Проблема осталась, так и не смог найти решения

2022-10-31 16:24 UTC, pavel-nyukalo requested changes

2022-10-31 16:24 UTC, pavel-niukalo commented on catalog.html
> +              </a>
Фокус в корзине немного вылезает за цифру

Макет:

![image](https://user-images.githubusercontent.com/52506235/199051588-0d3d91ba-9c32-4487-bc89-f4e14ac1d83f.png)

Сейчас:

![image](https://user-images.githubusercontent.com/52506235/199051643-e47eceab-d4b2-4d72-8d26-f7b60037fdaa.png)

2022-10-31 16:24 UTC, pavel-nyukalo commented on catalog.html
> +            </button>
Тут по стайлгайду у нас идет как будто один элемент

![image](https://user-images.githubusercontent.com/52506235/199052557-4a31f8b9-3218-4258-be9a-8914898ba379.png)

А сейчас они по-отдельности фокусируются

![image](https://user-images.githubusercontent.com/52506235/199052903-15038ed4-f03e-4f9c-a621-db82e3143ae2.png)

Предлагаю как реализовать:
у нас будет ссылка, а картинку просто рядом положить, не через кнопку. Таким образом иконка плюсика у нас будет своего рода декором, без интерактива.

А показ подменю как раз завяжем на фокус и ховер

```html
<a>
  Каталог товаров
  <svg></svg>
</a>
```

2022-10-31 16:24 UTC, pavel-nyukalo commented on catalog.html
> +                    fill="#000">
Нужно поправить ошибки валидатора

![image](https://user-images.githubusercontent.com/52506235/199055243-4cbeaec2-ae6f-48a8-89fd-153e0404b18e.png)

2022-10-31 16:24 UTC, pavel-nyukalo commented on catalog.html
> +                  <a href="product.html" class="product-card-link">
Кстати, если обнулить `outline` у ссылки при фокусу, то в целом выглядит по стайлгайду

![image](https://user-images.githubusercontent.com/52506235/199055617-40312453-eac3-4db9-94f1-191fad858603.png)


Вполне возможно, что проблема с фокусом была из-за того, что спека нам не говорит напрямую, можно ли вкладывать `div` в `a` и браузер мог по-своему добавить обработку этого и как-то сломать фокус

![image](https://user-images.githubusercontent.com/52506235/199055870-9ca72615-ed0b-42ad-9ed0-beaea4d86562.png)

2022-10-31 16:24 UTC, pavel-nyukalo commented on catalog.html
> +                    </button>
1. `span` выглядит лишним, можно сразу стилизовать кнопку
2. Лучше вернуть ссылку, как было. Потому что если у нас например не будет `js`, то мы сможем хотя бы перекинуть на страницу с другими товарами

2022-10-31 16:24 UTC, pavel-nyukalo commented on index.html
> +            </button>
Здесь так же как выше писал

2022-10-31 16:24 UTC, pavel-nyukalo commented on index.html
> +            <img class="product-showcase-img" src="images/slider-band.png" width="560" height="560"
Пройдись по всем картинкам и интерактивным элементам. В конце их описаний надо добавить точку

Вот критерии - [1](https://up.htmlacademy.ru/htmlcss/35/criteries#ALLY-01), [2](https://up.htmlacademy.ru/htmlcss/35/criteries#ALLY-02)

2022-10-31 17:11 UTC, mis3rably commented on catalog.html
> +                    fill="#000">
Исправил

2022-10-31 19:53 UTC, mis3rably commented on catalog.html
> +              </a>
Исправил

2022-10-31 19:54 UTC, mis3rably commented on catalog.html
> +                    </button>
Исправил

2022-10-31 19:55 UTC, mis3rably commented on catalog.html
> +                  <a href="product.html" class="product-card-link">
Исправил, теперь буду знать о таком

2022-10-31 19:55 UTC, mis3rably commented on catalog.html
> +            </button>
Исправил

2022-11-03 21:22 UTC, mis3rably commented on index.html
> +            </button>
Это единственное что я не понял что нужно исправить)

2022-11-03 21:28 UTC, mis3rably commented on index.html
> +            <img class="product-showcase-img" src="images/slider-band.png" width="560" height="560"
Проверил, должно быть всё в порядке

2022-11-03 21:31 UTC, mis3rably commented on index.html
> +            </a>
Не знаю, как сделать в соответствии с Стайлгайдом, получается кнопка при открытии меню с помощью мышки или таба меняется с плюс на минус. Как это сделать если картинка сделана как инлайн свг

2022-11-06 14:55 UTC, pavel-nyukalo commented on index.html
> +          <section class="modal-content flex">
Лишний отступ получился

2022-11-06 14:55 UTC, pavel-nyukalo commented on index.html
> +                  <button class="modal-input-number-button input-decrease"></button>
Здесь нужно скрытую подпись добавить

2022-11-06 14:55 UTC, pavel-nyukalo commented on index.html
> +                  <button class="modal-input-number-button input-increase"></button>
Тут так же

2022-11-06 14:55 UTC, pavel-nyukalo commented on index.html
> +              </fieldset>
Тут тоже отступы надо поправить

2022-11-06 14:55 UTC, pavel-nyukalo commented on catalog.html
> +              товаров</a>
Тут нам тоже надо добавить иконку

2022-11-06 14:55 UTC, pavel-nyukalo commented on index.html
> +            </button>
Тут я имел ввиду, как в `index.html`, вставить свг-шкой

2022-11-06 15:01 UTC, pavel-nyukalo requested changes

2022-11-06 15:01 UTC, pavel-niukalo commented on styles/styles.css
> +  background-color: #DCDCDC;
Для единообразия давай писать цвета в одном регистре - либо верхнем, либо нижнем. То есть сейчас идет смешение - `#c4c4c4` записан в нижнем, а `#DCDCDC` уже в верхнем

2022-11-06 15:01 UTC, pavel-niukalo commented on styles/styles.css
> +  background-image: url(../images/catalog-select-arrow.svg);
Кавычки в `url` стоит добавить, ждя надежности

2022-11-06 15:01 UTC, pavel-niukalo commented on styles/styles.css
> +}
Так же надо добавить состояние `disabled` для чекбоксов и радио. Если на макете нет, надо самому придумать

2022-11-06 15:04 UTC, mis3rably commented on styles/styles.css
> +  background-color: #DCDCDC;
Я хотел окончательно это сделать с linthtml в 10 разделе

2022-11-06 15:05 UTC, mis3rably commented on styles/styles.css
> +}
А active состояние (подчеркивание у текущей ссылки в хэдере) нужно добавить во время нажатия или в виде отдельного класса который будет добавляться когда пользователь переходит на эту страницу?

2022-11-06 15:06 UTC, mis3rably commented on styles/styles.css
> +  background-image: url(../images/catalog-select-arrow.svg);
Простите, всё время забываю(

2022-11-06 15:06 UTC, pavel-nyukalo commented on styles/styles.css
> +  background-color: #DCDCDC;
Тогда ладно, оставим на 10 раздел

2022-11-06 15:08 UTC, pavel-nyukalo commented on styles/styles.css
> +}
Вот это?

![image](https://user-images.githubusercontent.com/52506235/200178629-4cf62c7e-ec7c-4740-a931-60abc826853a.png)

Тут это отдельный класс, который будет показывать активную страницу. `:active` тут не подходит

2022-11-06 15:09 UTC, mis3rably commented on styles/styles.css
> +}
Да, я имел ввиду это. Буду исправлять

2022-11-06 15:11 UTC, pavel-nyukalo commented on index.html
> +            </a>
Хм, думал, что у нас там плюс нарисован как два отдельных тега (`path`). В таком случае можно было бы навесить класс, и скрывать одну черточку.

Можно попробовать поиграться в самой фигме и нарисовать самому такую конструкцию, либо как вариант еще, экспорнуть не +, а -, и псевдоэлементом нарисовать вертикальную палку, которую, опять же, скрывать

2022-11-06 15:14 UTC, mis3rably commented on index.html
> +            </a>
Понял, буду пробовать реализовать с помощью псевдоэлемента

2022-11-06 23:04 UTC, mis3rably commented on styles/styles.css
> +}
Исправил, также добавил disabled состояния

2022-11-07 14:09 UTC, pavel-nyukalo approved these changes

2022-11-07 14:10 UTC, merged