Завершаем вёрстку всех компонентов
htmlacademy-htmlcss/1976751-device-35 pull request #12
Opened 2022-11-07 14:33 UTC by mis3rably

2022-11-07 16:38 UTC, pavel-nyukalo requested changes

2022-11-07 16:38 UTC, pavel-nyukalo commented on styles/styles.css
> +  z-index: -1;
Это кстати отключает взаимодействия с элементами, сейчас не получится навести на ссылку, стрелки (не отработают состояния). С чем-то трудности возникли?

2022-11-07 16:38 UTC, pavel-nyukalo commented on styles/styles.css
> +.shopping-cart-wrapper {
В каталоге немного поехало кстати

![image](https://user-images.githubusercontent.com/52506235/200364154-691d2f73-7af8-4ef3-8970-0f2f97c79a46.png)

2022-11-07 16:38 UTC, pavel-nyukalo commented on index.html
> +              </div>
Укажу сюда:

1. На макете стоит 1, надо в value тоже записать, чтобы было по макету

![image](https://user-images.githubusercontent.com/52506235/200364434-83f13d48-ca38-4e74-993c-09083fb04a14.png)

2. И еще вот такая история у нас есть, ее тоже надо реализовать

![image](https://user-images.githubusercontent.com/52506235/200364654-b3af22e9-2969-4158-8f94-e9f956e1ca04.png)

3. Упустил это где-то при проверках, но всем кнопкам надо явно указать `type`. Например, у кнопок увеличить/уменьшить кол-во нет его, и нажатие на эти кнопки пытается отправить форму (поскольку без указанного `type` он становится равным `submit`)

2022-11-07 17:05 UTC, mis3rably commented on styles/styles.css
> +  z-index: -1;
Ой, забыл убрать. Экспериментировал с z-index с кнопками у слайдера. Проверял на переполнение главную страницу и открывая drop-down меню поверх него идут кнопки. Пытался разобраться как исправить

2022-11-07 17:07 UTC, mis3rably commented on index.html
> +              </div>
Тултип сделан, но почему то не при ховере не отображается. Я проверил через девтулс если поставить ховер иконке тултипа он появляется, навожу мышкой — ничего не происходит. Хотя когда только сделал работало

2022-11-07 21:19 UTC, mis3rably commented on styles/styles.css
> +.shopping-cart-wrapper {
Исправил, забыл дублировать обёртку в каталог

2022-11-07 21:19 UTC, mis3rably commented on styles/styles.css
> +  z-index: -1;
Исправил

2022-11-07 22:22 UTC, mis3rably commented on index.html
> +              </div>
Исправил

2022-11-08 10:00 UTC, pavel-niukalo approved these changes

2022-11-08 10:00 UTC, merged