Проверяем макет по критериям
htmlacademy-htmlcss/1976751-device-35 pull request #13
Opened 2022-11-08 21:55 UTC by mis3rably

2022-11-09 11:56 UTC, pavel-nyukalo requested changes
Вот у этих кнопок нет `type`

![image](https://user-images.githubusercontent.com/52506235/200822404-cb9ed0c2-4a39-4674-81b1-0430554862f2.png)

![image](https://user-images.githubusercontent.com/52506235/200822466-7827b8ae-8861-44ff-9d49-9d2229f45c15.png)

2022-11-09 11:56 UTC, pavel-nyukalo commented on catalog.html
> +              <span class="main-header-page-navigation-button-link-text">Каталог товаров</span>
В каталоге не получается выбрать доп. меню. Как только мышка уходит с "Каталог товаров" доп. меню прячется. На главной все хорошо работает

Так же кстати работает поповер у "Корзина"

2022-11-09 11:56 UTC, pavel-nyukalo commented on index.html
> +                    <img width="39" height="43" class="popover-cart-item-img" src="images/products/product-amateur.jpg" alt="Товар Любительская селфи-палка.">
Напишу сюда.
Для защиты давай скроем (именно скроем, не удалим/закомментируем из разметки) два других слайда и вот это

![image](https://user-images.githubusercontent.com/52506235/200818778-7fa13ee1-2143-4c9d-ad0f-e4086b641596.png)

2022-11-09 11:56 UTC, pavel-nyukalo commented on styles/styles.css
> +  font-weight: 700;
Лейблам лучше не отключать `pointer-events: none`, поскольку при нажатии на текст браузер перебросит фокус в инпут и это нормальное поведение

2022-11-09 12:00 UTC, mis3rably commented on index.html
> +                    <img width="39" height="43" class="popover-cart-item-img" src="images/products/product-amateur.jpg" alt="Товар Любительская селфи-палка.">
Скрыть лучше через visually-hidden или display: none?

2022-11-09 12:00 UTC, pavel-nyukalo commented on index.html
> +                    <img width="39" height="43" class="popover-cart-item-img" src="images/products/product-amateur.jpg" alt="Товар Любительская селфи-палка.">
`display: none`

2022-11-09 12:01 UTC, mis3rably commented on styles/styles.css
> +  font-weight: 700;
Я убрал потому что ховер у лейбла странно работал, как будто каждое движение мыши на лейбле включало и отключало ховер

2022-11-09 12:02 UTC, pavel-nyukalo commented on styles/styles.css
> +  font-weight: 700;
Это нормальное поведение

2022-11-09 12:03 UTC, mis3rably commented on catalog.html
> +              <span class="main-header-page-navigation-button-link-text">Каталог товаров</span>
Ещё есть вопрос насчёт поповера, когда мышка уходит с ссылки на корзину то поповер пропадает, и из-за этого достаточно трудно попасть по поповеру так как между ним и ссылкой есть небольшое расстояние. Оставить так или можно как-то исправить?

2022-11-10 06:44 UTC, pavel-nyukalo commented on catalog.html
> +              <span class="main-header-page-navigation-button-link-text">Каталог товаров</span>
Это можно исправить за счет добавления обертки для поповера, у которой отступ (по макету, как раз вот это небольшое расстояние) будет паддингом (именно им, поскольку если дать марджин то будет такое же поведение).

То есть получается ссылка и вот эта обертка будут вплотную друг к другу и за счет этого мышка ховер будет отрабатывать

2022-11-10 07:07 UTC, pavel-nyukalo approved these changes

2022-11-10 07:07 UTC, merged